pipelines:
  - name: Sanity_Trigger
    steps:
    - name: trigger
      type: Bash
      configuration:
        outputResources:
          - name: trigger_basic
          - name: run_varaibles_sanity
      execution:
        onStart: 
          - write_output trigger_basic "triggerRunId=${run_id}"
          - write_output trigger_basic "qualityGateStep=basic_sanity_gate"
          - write_output run_varaibles_sanity "triggerRunId=${run_id}"
          - write_output run_varaibles_sanity "qualityGateStep=basic_run_varaibles_gate"
  
    - name: basic_sanity_gate
      type: Bash
      configuration:
        requiresApproval: true
        inputResources:
          - name: trigger_basic
      execution:
        onExecute:
          - echo "Basic sanity done"

    - name: basic_run_varaibles_gate
      type: Bash
      configuration:
        requiresApproval: true
        inputResources:
          - name: run_varaibles_sanity
      execution:
        onExecute:
          - echo "Basic sanity done"


    - name: fail_if_sanity_failed
      type: Bash
      configuration:
        inputSteps:
          - name: basic_sanity_gate
            status:
            - "failure"
            - "error"
            - "skipped"
            - "cancelled"
            - "timeout"
          - name: basic_run_varaibles_gate
            status:
              - "failure"
              - "error"
              - "skipped"
              - "cancelled"
              - "timeout"
      execution:
        onExecute:
          - exit 1
      
  - name: Sanity_Basic
    steps:
      - name: trigger_basic
        type: Bash
        configuration:
          inputResources:
            - name: trigger_basic
        execution:
          onStart:
            - echo "triggerRunId is ${triggerRunId}"
            - printenv
      - name: approveStep
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_basic
          inputResources:
            - name: this_repo
              trigger: false
            - name: trigger_basic
          integrations:
            - name: sanity_platform
        execution:
          onStart:
            - pushd ${res_this_repo_resourcePath}/scripts
            - npm ci
            - export API_URL="${int_sanity_platform_url}/pipelines/api/v1"
            - export API_TOKEN="Bearer ${int_sanity_platform_accessToken}"
            - node index.js sanityGate --stepName $qualityGateStep --runId $triggerRunId --approved --comment "approved my api"

