resources:
  - name: runVariablesResInt1
    type: PropertyBag
    configuration:
      some_key: some_value
  - name: runVariablesResource1
    type: PropertyBag
    configuration:
      some_key: some_value
pipelines:
  - name: test_run_variables
    steps:
    - name: stepA
      type: Bash
      configuration:
        outputResources:
          - name: runVariablesResource1
      execution:
        onExecute:
          - add_run_variables "keyA=valueA"
    - name: stepB
      type: Bash
      configuration:
        affinityGroup: group
        inputResources:
          - name: runVariablesResource1
        outputResources:
          - name: runVariablesResInt1
      execution:
        onExecute:
          - echo $keyA
          - add_run_variables "keyA=valueB"
    - name: stepD
      type: Bash
      configuration:
        affinityGroup: group
      execution:
        onExecute:
          - echo $keyA
          - add_run_variables "keyA=valueC"
    - name: stepC
      configuration:
        affinityGroup: group
        inputSteps:
          - name: stepD
        inputResources:
          - name: runVariablesResInt1
          - name: runVariablesResource1
      type: Bash
      execution:
        onExecute:
          - echo $keyA