pipelines:
  - name: Sanity_Env_Trigger
    steps:
    - name: trigger
      type: Bash
      configuration:
        outputResources:
          - name: env_sanity
      execution:
        onStart: 
          - write_output env_sanity "triggerRunId=${run_id}"
          - write_output env_sanity "qualityGateStep=env_sanity_gate"
  
    - name: env_sanity_gate
      type: Bash
      configuration:
        requiresApproval: true
        inputResources:
          - name: env_sanity
      execution:
        onExecute:
          - echo "Basic sanity done"

    - name: approve_sanity
      type: Bash
      configuration:
        inputSteps:
          - name: environment_variable_step1
        inputResources:
          - name: this_repo
          - name: env_sanity
        integrations:
          - name: sanity_platform
      execution:
        onExecute:
          - pushd ${res_this_repo_resourcePath}/scripts
          - npm ci
          - export API_URL="${int_sanity_platform_url}/pipelines/api/v1"
          - export API_TOKEN="Bearer ${int_sanity_platform_accessToken}"
          - node index.js sanityGate --stepName $qualityGateStep --runId $triggerRunId --approved --comment "approved all tests passed"

      - name: reject_sanity
        configuration:
          inputSteps:
            - name: approve_runtime_sanity
              status:
                - "failure"
                - "error"
                - "skipped"
                - "cancelled"
                - "timeout"
          inputResources:
            - name: this_repo
            - name: runtime_sanity
          integrations:
            - name: sanity_platform
        type: Bash
        execution:
          onExecute:
            - pushd ${res_this_repo_resourcePath}/scripts
            - npm ci
            - export API_URL="${int_sanity_platform_url}/pipelines/api/v1"
            - export API_TOKEN="Bearer ${int_sanity_platform_accessToken}"
            - node index.js sanityGate --stepName $qualityGateStep --runId $triggerRunId --comment "rejected because few of the tests failed"